// <auto-generated />
using System;
using HospitalEpidemiology;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace HospitalEpidemiology.Migrations
{
    [DbContext(typeof(HospitalEpidemiologyDb))]
    [Migration("20230315165710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("HospitalEpidemiology.Model.BedLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_bed_locations");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_bed_locations_room_id");

                    b.ToTable("bed_locations", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_hospitals");

                    b.ToTable("hospitals", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.PatientBedLocationStay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int>("BedLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("bed_location_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<NpgsqlRange<DateTime>>("Stay")
                        .HasColumnType("tstzrange")
                        .HasColumnName("stay");

                    b.HasKey("id")
                        .HasName("pk_patient_bed_location_stays");

                    b.HasIndex("BedLocationId")
                        .HasDatabaseName("ix_patient_bed_location_stays_bed_location_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_bed_location_stays_patient_id");

                    b.ToTable("patient_bed_location_stays", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.PatientRoomStay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<NpgsqlRange<DateTime>>("Stay")
                        .HasColumnType("tstzrange")
                        .HasColumnName("stay");

                    b.HasKey("id")
                        .HasName("pk_patient_room_stays");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_room_stays_patient_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_patient_room_stays_room_id");

                    b.ToTable("patient_room_stays", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.PatientUnitStay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<NpgsqlRange<DateTime>>("Stay")
                        .HasColumnType("tstzrange")
                        .HasColumnName("stay");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("id")
                        .HasName("pk_patient_unit_stays");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_unit_stays_patient_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_patient_unit_stays_unit_id");

                    b.ToTable("patient_unit_stays", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_rooms_unit_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer")
                        .HasColumnName("hospital_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("HospitalId")
                        .HasDatabaseName("ix_units_hospital_id");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.BedLocation", b =>
                {
                    b.HasOne("HospitalEpidemiology.Model.Room", "Room")
                        .WithMany("BedLocations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bed_locations_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.PatientBedLocationStay", b =>
                {
                    b.HasOne("HospitalEpidemiology.Model.BedLocation", "BedLocation")
                        .WithMany("PatientStays")
                        .HasForeignKey("BedLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_bed_location_stays_bed_locations_bed_location_id");

                    b.HasOne("HospitalEpidemiology.Model.Patient", "Patient")
                        .WithMany("BedLocationStays")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_bed_location_stays_patients_patient_id");

                    b.Navigation("BedLocation");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.PatientRoomStay", b =>
                {
                    b.HasOne("HospitalEpidemiology.Model.Patient", "Patient")
                        .WithMany("RoomStays")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_room_stays_patients_patient_id");

                    b.HasOne("HospitalEpidemiology.Model.Room", "Room")
                        .WithMany("PatientStays")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_room_stays_rooms_room_id");

                    b.Navigation("Patient");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.PatientUnitStay", b =>
                {
                    b.HasOne("HospitalEpidemiology.Model.Patient", "Patient")
                        .WithMany("UnitStays")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_unit_stays_patients_patient_id");

                    b.HasOne("HospitalEpidemiology.Model.Unit", "Unit")
                        .WithMany("PatientStays")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_unit_stays_units_unit_id");

                    b.Navigation("Patient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Room", b =>
                {
                    b.HasOne("HospitalEpidemiology.Model.Unit", "Unit")
                        .WithMany("Rooms")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_units_unit_id");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Unit", b =>
                {
                    b.HasOne("HospitalEpidemiology.Model.Hospital", "Hospital")
                        .WithMany("Units")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_units_hospitals_hospital_id");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.BedLocation", b =>
                {
                    b.Navigation("PatientStays");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Hospital", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Patient", b =>
                {
                    b.Navigation("BedLocationStays");

                    b.Navigation("RoomStays");

                    b.Navigation("UnitStays");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Room", b =>
                {
                    b.Navigation("BedLocations");

                    b.Navigation("PatientStays");
                });

            modelBuilder.Entity("HospitalEpidemiology.Model.Unit", b =>
                {
                    b.Navigation("PatientStays");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
